Map<String, String> enUs = {
  'unauthorized': 'Login to view all the features',
  'company': 'Company',
  'office': 'Office',
  'report': 'Report',
  'download': 'Download',
  'next': 'Next',
  'add': 'Add',
  'edit': 'Edit',
  'delete': 'Delete',
  'submit': 'Submit',
  'save': 'Simpan',
  'total_asset': 'Total Asset',
  'total_component': 'Total Component',
  'total_maintenance': 'Total Maintenance',
  'total_staff': 'Total Staff',
  'asset_by_category': 'Asset by Category',
  'asset_by_status': 'Asset by Status',
  'submission': 'Submission',
  'asset_activity': 'Asset Activity',
  'component_activity': 'Component Activity',
  'dashboard': 'Dashboard',
  'asset': 'Asset',
  'reminder': 'Reminder',
  'depreciation': 'Depreciation',
  'account': 'Account',
  'ready': 'Ready',
  'what_are_you_looking_for': 'What are you looking for?',
  'assign': 'Assign',
  'un_assign': 'Un-Assign',
  'tag_asset': 'Tag Asset',
  'category': 'Category',
  'assigned': 'Assigned',
  'location': 'Location',
  'detail_asset': 'Detail Asset',
  'type': 'Type',
  'status': 'Status',
  'details': 'Details',
  'component': 'Component',
  'maintenance': 'Maintenance',
  'history': 'History',
  'file': 'File',
  'log_activity': 'Log Activity',
  'group': 'Group',
  'sub_category': 'Sub Category',
  'person_on_charge': 'Person on charge',
  'supplier': 'Supplier',
  'update_at': 'Update at',
  'create_at': 'create at',
  'description': 'Descriptions',
  'no_data_available': 'No data available',
  'employee': 'Employee',
  'period': 'Period',
  'depreciation_percentage': 'Depreciation Percentage',
  'amount': 'Amount',
  'accumulated_depreciation': 'Accumulated Depreciation',
  'ending_book_value': 'Ending Book Value',
  'component_quantity': 'Component Quantity',
  'available_component': 'Available Component',
  'cost': 'cost',
  'asset_value': 'Asset Value',
  'name': 'Name',
  'building': 'Building',
  'floor': 'Floor',
  'room': 'Room',
  'brand': 'Brand',
  'purchase_date': 'Purchase Date',
  'warranty': 'Warranty',
  'upload_image_asset': 'Upload image jpeg, jpg, png (Max 4 MB)',
  'days': 'Days',
  'month': 'Months',
  'years': 'Years',
  'select_item_label': 'Select @value',
  'select_item_field': 'Select a @value here..',
  'please_in_field': 'Please fill in @value',
  'write_in_field': 'Write the @value here..',
  'depreciation_method': 'Depreciation Method',
  'depreciation_value': 'Depreciation Value',
  'cost_asset': 'Cost Asset',
  'cost_component': 'Cost Component',
  'email': 'email',
  'department': 'Department',
  'position': 'Position',
  'phone': 'Phone',
  'address': 'Address',
  'add_depreciation': 'Add Depreciation',
  'edit_depreciation': 'Edit Depreciation',
  'add_asset': 'Add Asset',
  'edit_asset': 'Edit Asset',
  'priority': 'Priority',
  'data': 'Date',
  'successful_': 'Successful @value',
  'assign_date': 'Assign Date',
  'serial': 'Serial',
  'delete_depreciation': 'Delete Depreciation',
  'delete_asset': 'Delete Asset',
  'dialog_delete_asset': 'Are you going to delete the @value Asset data?',
  'dialog_delete_depreciation': 'Are you going to delete the @value Depreciation data?',
  'quantity': 'Quantity',
  'available': 'Available',
  'start_date': 'Start Date',
  'end_date': 'End Date',
  'staff': 'Staff',
  'straight_line_method': 'Straight Line Method',
  'decreasing_balance_method': 'Decreasing balance Method',
  'date': 'Date',
  'cancel': 'Cancel',
  'add_file': 'Add File',
  'yes_delete': 'Yes, delete',
  'title': 'Title',
  'needs': 'Needs',
  'date_needed': 'Date Needed',
  'purchase_order': 'Purchase Order',
  'lending': 'Lending',
  'monitoring': 'Monitoring',
  'menu': 'Menu',
  'all': 'All',
  'asset_management': 'Asset Management',
  'name_reminder': 'Name Reminder',
  'repeat': 'Repeat',
  'every_day': 'Every day',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'yearly': 'Yearly',
  'review': 'review',
  'approve': 'Approve',
  'lending_asset': 'Landing Asset',
  'lending_date': 'Landing Date',
  'return_date': 'Return Date',
  'submission_step_2': 'Approved by the relevant superior',
  'submission_step_3': 'GA looking for suppliers to submit',
  'submission_step_4': 'Approved by related superior',
  'submission_step_5': 'Approved by Finance',
  'submission_step_4&5': 'Approved by related superior & finance',
  'submission_step_6': 'Asset procurement',
  'submission_step_7': 'Asset procurement',
  'submission_step_0': 'Submission Asset Complete',
  'On Process': 'On Process',
  'Approved': 'Approved',
  'Rejected': 'Rejected',
  'Complete': 'Completed',
  'added_from': 'Added From',
  'date_used': 'Date Used',
  'tracking': 'Tracking',
  'yes,approved': 'Yes, Approved',
  'find_supplier': 'Find Supplier',
  'see_all_monitoring_lists': 'See all monitoring lists',
  'upload_file_find_supplier': 'Upload file jpeg, jpg, png, doc, docx, xls, xls (Max 4 MB)',
  'note': 'Note',
  'data_supplier': 'Data Supplier',
  'upload_document': 'Upload Document',
  'reject_submission': 'Reject submissions',
  'approve_submission': 'Approve submissions',
  'reason': 'Reason',
  'send': 'Send',
  'comment': 'Komentar',
  'choose_approved_supplier': 'Choose approved supplier',
  'choose_supplier': 'Choose Supplier',
  'info_choose_supplier': 'Please select 1 supplier to forward to purchase order. ',
  'submission_details': 'Submission Details',
  'info_create_purchase_order_1': "You don't currently have a list of items to purchase, ",
  'info_create_purchase_order_2': "click here",
  'info_create_purchase_order_3': " to add a purchase list",
  'info_po_is_empty': 'Please fill in the items to purchase',
  'added': 'Added',
  'insert_the_discount_amount_and_tax_your_assets': 'Insert the discount amount and tax your assets',
  'insert_discount_and_tax_here': 'Insert discount and tax here',
  'discount': 'Discount',
  'total_discount': 'Total Discount',
  'total_payment': 'Total Payment',
  'tax': 'Tax',
  'total_tax': 'Total Tax',
  'form_purchase': 'Form Purchase',
  'asset_name': 'Asset Name',
  'create_purchase_order': 'Create Purchase Order',
  'paid': 'Paid',
  'un_paid': 'Un-Paid',
  'upload_invoice': 'Upload Invoice',
  'create_submission': 'Tambah Pengajuan',
  'submission_rejected': 'Submission rejected',
  'submission_approved': 'Submission Approved',
  'submission_selected_supplier': 'submission_selected_supplier',
  'set_supplier': 'Set supplier',
  'please_add_a_suppliers': 'Please add a supplier',
  'created_purchase_order': 'Created purchase order',
  'please_fill_in_the_items_to_purchase': 'Please fill in the items to purchase',
  'total': 'Total',
  'purchase': 'Purchase',
  'sub_total': 'Sub Total',
  'upload_file': 'Upload File',
  'choose_file': 'Choose file',
  'upload': 'Upload',
  'please_add_file': 'Please add file',
  'resubmission': 'Re-Submission',
  'subject': 'Subject',
  'items': 'Items',
  'purchase_details': 'Purchase Details',
  'sorry_you_dont_have_access': "Sorry, you don't have access",
  'component_name': "Component Name",
};