Map<String, String> enUs = {
  'company': 'Company',
  'office': 'Office',
  'organization_structure': 'Organization Structure',
  'employee_list': 'Employees List',
  'schedule': 'Schedule',
  'announcement': 'Announcement',
  'e-learning': 'E-Learning',
  'report': 'Report',
  'monitor_performance': 'Monitor Performance',
  'download': 'Download',
  'what_service_are_you_looking_for': 'what service are you looking for?',
  'add_balance_you_can_change_company': 'add balance, you can change company',
  'next': 'Next',
  'add': 'Add',
  'edit': 'Edit',
  'delete': 'Delete',
  'submit': 'Submit',
  'save': 'Simpan',
  'info_add_structure': 'Add a Position in the Structure or Position of your choice.',
  'info_edit_structure': 'Edit a Position in the Structure or Position of your choice.',
  'info_add_edit_position': 'Silakan tambah nama jabatan fungsional yang ada di perusahaan Anda. Jabatan Fungsional adalah jabatan teknis yang tidak tercantum dalam struktur organisasi, tetapi dari sudut pandang fungsinya sangat diperlukan dalam pelaksanaan tugas-tugas pokok organisasi. Seperti guru, dokter, perawat, peneliti, perencana, pranata komputer, statistik, pranata laboratorium pendidikan, dan tenaga magang.',
  'enter_name_structure': 'Enter name structure',
  'please_enter_name_structure': 'please enter name structure',
  'choose_level_structure': 'Choose level structure',
  'please_choose_level_structure': 'please choose level structure',
  'structure_organization': 'Structure organization',
  'structure_name': 'Structure name',
  'functional_position_name': 'Functional position name',
  'enter_name_functional_position': 'Enter name structure',
  'please_enter_name_functional_position': 'please enter name structure',
  'structure_level': 'Structure level',
  'structure': 'Structure',
  'structure_delete_success': 'Structure delete success',
  'created_structure_successful': 'Created structure successful',
  'position_delete_success': 'Position name delete success',
  'created_functional_position_successful': 'Created functional position successful',
  'update_structure_successful': 'Update structure successful',
  'add_structure': 'Add structure',
  'edit_structure': 'Edit structure',
  'delete_structure': 'Delete structure',
  'position': 'Position',
  'position_functional': 'Position functional',
  'position_name': 'Position name',
  'action': 'Action',
  'add_position_function': 'Tambah posisi fungsional',
  'edit_position_function': 'Ubah posisi fungsional',
  'add_position': 'Add position',
  'add_office': 'Add office',
  'edit_position': 'Edit position',
  'edit_office': 'Edit office',
  'delete_position': 'Delete position',
  'info_office': 'Information office'
};