Map<String, String> idId = {
  'unauthorized': 'Masuk untuk melihat semua fitur',
  'company': 'Perusahaan',
  'office': 'Kantor',
  'download': 'Unduh',
  'next': 'Lanjut',
  'add': 'Tambah',
  'edit': 'Ubah',
  'delete': 'Hapus',
  'submit': 'Ajukan',
  'save': 'Simpan',
  'total_asset': 'Total Aset',
  'total_component': 'Total Komponen',
  'total_maintenance': 'Total Pemeliharaan',
  'total_staff': 'Total Staf',
  'asset_by_category': 'Aset Berdasarkan Categori',
  'asset_by_status': 'Aset Berdasarkan Status',
  'submission': 'Pengajuan',
  'recent_asset_activity': 'Aktivitas Aset Terakhir',
  'recent_component_activity': 'Aktivitas Komponent Terakhir',
  'dashboard': 'Dashboard',
  'asset': 'Aset',
  'reminder': 'Pengingat',
  'depreciation': 'Depresiasi',
  'account': 'Akun',
  'ready': 'Siap',
  'what_are_you_looking_for': 'Kamu lagi cari apa?',
  'assign': 'Assign',
  'un_assign': 'Un-Assign',
  'tag_asset': 'Tag Asset',
  'category': 'Katagori',
  'assigned': 'Assigned',
  'location': 'Lokasi',
  'detail_asset': 'Detail Aset',
  'type': 'Tipe',
  'status': 'Status',
  'details': 'Details',
  'component': 'Komponen',
  'maintenance': 'Pemeliharaan',
  'history': 'Riwayat',
  'file': 'File',
  'log_activity': 'Log Aktivitas',
  'group': 'Kelompok',
  'sub_category': 'Sub Kategori',
  'person_on_charge': 'Penanggung Jawab',
  'supplier': 'Pemasok',
  'update_at': 'Diperbarui pada',
  'create_at': 'Dibuat pada',
  'description': 'Deskripsi',
  'no_data_available': 'Tidak Ada Data Tersedia',
  'employee': 'Karyawan',
  'period': 'Periode',
  'depreciation_percentage': 'Persentase Depresiasi',
  'amount': 'Jumlah',
  'accumulated_depreciation': 'Akumulasi Depresiasi',
  'ending_book_value': 'Nilai Buku Akhir',
  'component_quantity': 'Jumlah Komponen',
  'available_component': 'Jumlah Tersedia',
  'cost': 'Biaya',
  'asset_value': 'Nilai Aset',
  'name': 'Nama',
  'building': 'Gedung',
  'floor': 'Lantai',
  'room': 'Ruangan',
  'brand': 'Merk',
  'purchase_date': 'Tanggal Pembelian',
  'warranty': 'Garansi',
  'upload_image_asset': 'Unduh gambar jpeg, jpg, png, (Max 4 MB)', //'Upload image jpeg, jpg, png (Max 4 MB)',
  'days': 'Hari',
  'month': 'Bulan',
  'years': 'Tahun',
  'select_item_label': 'Pilih @value',  //Please fill in @value
  'select_item_field': 'Pilih @value disini..', //select a @value here..
  'please_in_field': 'Mohon isi @value', //Please fill in @value
  'write_in_field': 'Tulis @value disini..', //Write the @value here..
  'depreciation_method': 'Metode Depresiasi',
  'depreciation_value': 'Nilai Depresiasi',
  'cost_asset': 'Biaya Aset',
  'cost_component': 'Biaya Komponen',
  'email': 'Email',
  'department': 'Departemen',
  'position': 'Posisi',
  'phone': 'Telepon',
  'address': 'Alamat',
  'add_depreciation': 'Tambah Depresiasi',
  'edit_depreciation': 'Ubah Depresiasi',
  'add_asset': 'Tambah Aset',
  'edit_asset': 'Ubah Aset',
  'priority': 'Prioritas',
  'data': 'Tanggal',
  'successful_': 'Berhasil @value',
  'assign_date': 'Tanggal Assign',
  'serial': 'Serial',
  'delete_depreciation': 'Hapus Depresiasi',
  'delete_asset': 'Hapus Aset',
  'dialog_delete_asset': 'Apakah Anda akan menghapus data Aset @value?',
  'dialog_delete_depreciation': 'Apakah Anda akan menghapus data Depresiasi @value?',
  'quantity': 'Quantity',
  'available': 'Available',
  'start_date': 'Tanggal Mulai',
  'end_date': 'Tanggal Akhir',
  'staff': 'Staff',
  'straight_line_method': 'Metode Garis Lurus',
  'decreasing_balance_method': 'Metode Saldo Menurun',
  'date': 'Tanggal',
  'cancel': 'Batal',
  'add_file': 'Tambah File',
  'yes_delete': 'Ya, hapus'
};