Map<String, String> idId = {
  'company': 'Perusahaan',
  'office': 'Kantor',
  'organization_structure': 'Struktur Organisasi',
  'employee_list': 'Daftar Karyawan',
  'schedule': 'Jadwal',
  'announcement': 'Pengumuman',
  'e-learning': 'E-Pembelajaran',
  'report': 'Laporan',
  'monitor_performance': 'Memantau Kinerja',
  'download': 'Unduh',
  'what_service_are_you_looking_for': 'kamu lagi cari layanan apa?',
  'add_balance_you_can_change_company': 'tambahkan saldo, kamu bisa berpindah perusahaan',
  'next': 'Lanjut',
  'add': 'Tambah',
  'edit': 'Ubah',
  'delete': 'Hapus',
  'submit': 'Ajukan',
  'save': 'Simpan',
  'info_add_structure': 'Tambahkan Jabatan di Strukture ataupun Jabatan Anda pilih.',
  'info_edit_structure': 'Ubah Jabatan di Strukture ataupun Jabatan Anda pilih.',
  'info_add_edit_position': 'Silakan tambah nama jabatan fungsional yang ada di perusahaan Anda. Jabatan Fungsional adalah jabatan teknis yang tidak tercantum dalam struktur organisasi, tetapi dari sudut pandang fungsinya sangat diperlukan dalam pelaksanaan tugas-tugas pokok organisasi. Seperti guru, dokter, perawat, peneliti, perencana, pranata komputer, statistik, pranata laboratorium pendidikan, dan tenaga magang.',
  'enter_name_structure': 'Masukkan struktur nama',
  'please_enter_name_structure': 'silakan masukkan struktur nama',
  'choose_level_structure': 'Pilih struktur tingkat',
  'please_choose_level_structure': 'silahkan pilih struktur tingkat',
  'structure_organization': 'Struktur organisasi',
  'structure_name': 'Nama Struktur',
  'functional_position_name': 'Nama jabatan fungsional',
  'enter_name_functional_position': 'Tulis nama jabatan fungsional disini',
  'please_enter_name_functional_position': 'please enter name structure',
  'structure_level': 'Level Struktur',
  'structure': 'Struktur',
  'structure_delete_success': 'Hapus struktur berhasil',
  'position_delete_success': 'Hapus nama posisi berhasil',
  'created_structure_successful': 'Struktur dibuat berhasil',
  'update_structure_successful': 'Strukture diubah berhasil',
  'created_functional_position_successful': 'Created functional position successful',
  'add_structure': 'Tambah struktur',
  'edit_structure': 'Ubah struktur',
  'delete_structure': 'Hapus struktur',
  'position': 'Jabatan',
  'position_functional': 'Posisi fungsional',
  'position_name': 'Nama Posisi',
  'action': 'Aksi',
  'add_position_function': 'Tambah jabatan fungsional',
  'edit_position_function': 'Ubah posisi fungsional',
  'add_position': 'Tambah jabatan',
  'add_office': 'Tambah kantor',
  'edit_position': 'Ubah jabatan',
  'edit_office': 'Ubah kantor',
  'delete_position': 'Hapus jabatan',
  'info_office': 'Informasi kantor'
};