Map<String, String> idId = {
  'unauthorized': 'Masuk untuk melihat semua fitur',
  'company': 'Perusahaan',
  'office': 'Kantor',
  'report': 'Report',
  'download': 'Unduh',
  'next': 'Lanjut',
  'add': 'Tambah',
  'edit': 'Ubah',
  'delete': 'Hapus',
  'submit': 'Ajukan',
  'save': 'Simpan',
  'total_asset': 'Total Aset',
  'total_component': 'Total Komponen',
  'total_maintenance': 'Total Pemeliharaan',
  'total_staff': 'Total Staf',
  'asset_by_category': 'Aset Berdasarkan Categori',
  'asset_by_status': 'Aset Berdasarkan Status',
  'submission': 'Pengajuan',
  'recent_asset_activity': 'Aktivitas Aset Terakhir',
  'recent_component_activity': 'Aktivitas Komponent Terakhir',
  'dashboard': 'Dashboard',
  'asset': 'Aset',
  'reminder': 'Pengingat',
  'depreciation': 'Penyusutan',
  'account': 'Akun',
  'ready': 'Siap',
  'what_are_you_looking_for': 'Kamu lagi cari apa?',
  'assign': 'Assign',
  'un_assign': 'Un-Assign',
  'tag_asset': 'Tag Asset',
  'category': 'Katagori',
  'assigned': 'Assigned',
  'location': 'Lokasi',
  'detail_asset': 'Detail Aset',
  'type': 'Tipe',
  'status': 'Status',
  'details': 'Details',
  'component': 'Komponen',
  'maintenance': 'Pemeliharaan',
  'history': 'Riwayat',
  'file': 'File',
  'log_activity': 'Log Aktivitas',
  'group': 'Kelompok',
  'sub_category': 'Sub Kategori',
  'person_on_charge': 'Penanggung Jawab',
  'supplier': 'Pemasok',
  'update_at': 'Diperbarui pada',
  'create_at': 'Dibuat pada',
  'description': 'Deskripsi',
  'no_data_available': 'Tidak Ada Data Tersedia',
  'employee': 'Karyawan',
  'period': 'Periode',
  'depreciation_percentage': 'Persentase Depresiasi',
  'amount': 'Jumlah',
  'accumulated_depreciation': 'Akumulasi Depresiasi',
  'ending_book_value': 'Nilai Buku Akhir',
  'component_quantity': 'Jumlah Komponen',
  'available_component': 'Jumlah Tersedia',
  'cost': 'Biaya',
  'asset_value': 'Nilai Aset',
  'name': 'Nama',
  'building': 'Gedung',
  'floor': 'Lantai',
  'room': 'Ruangan',
  'brand': 'Merk',
  'purchase_date': 'Tanggal Pembelian',
  'warranty': 'Garansi',
  'upload_image_asset': 'Unduh gambar jpeg, jpg, png, (Max 4 MB)', //'Upload image jpeg, jpg, png (Max 4 MB)',
  'days': 'Hari',
  'month': 'Bulan',
  'years': 'Tahun',
  'select_item_label': 'Pilih @value',  //Please fill in @value
  'select_item_field': 'Pilih @value disini..', //select a @value here..
  'please_in_field': 'Mohon isi @value', //Please fill in @value
  'write_in_field': 'Tulis @value disini..', //Write the @value here..
  'depreciation_method': 'Metode Depresiasi',
  'depreciation_value': 'Nilai Depresiasi',
  'cost_asset': 'Biaya Aset',
  'cost_component': 'Biaya Komponen',
  'email': 'Email',
  'department': 'Departemen',
  'position': 'Posisi',
  'phone': 'Telepon',
  'address': 'Alamat',
  'add_depreciation': 'Tambah Depresiasi',
  'edit_depreciation': 'Ubah Depresiasi',
  'add_asset': 'Tambah Aset',
  'edit_asset': 'Ubah Aset',
  'priority': 'Prioritas',
  'data': 'Tanggal',
  'successful_': 'Berhasil @value',
  'assign_date': 'Tanggal Assign',
  'serial': 'Serial',
  'delete_depreciation': 'Hapus Depresiasi',
  'delete_asset': 'Hapus Aset',
  'dialog_delete_asset': 'Apakah Anda akan menghapus data Aset @value?',
  'dialog_delete_depreciation': 'Apakah Anda akan menghapus data Depresiasi @value?',
  'quantity': 'Quantity',
  'available': 'Available',
  'start_date': 'Tanggal Mulai',
  'end_date': 'Tanggal Akhir',
  'staff': 'Staff',
  'straight_line_method': 'Metode Garis Lurus',
  'decreasing_balance_method': 'Metode Saldo Menurun',
  'date': 'Tanggal',
  'cancel': 'Batal',
  'add_file': 'Tambah File',
  'yes_delete': 'Ya, hapus',
  'title': 'Judul',
  'needs': 'Kebutuhan',
  'date_needed': 'Tanggal Dibutuhkan',
  'purchase_order': 'Pengajuan pembelian',
  'lending': 'Peminjaman',
  'monitoring': 'Monitoring',
  'menu': 'Menu',
  'all': 'Semua',
  'asset_management': 'Aset Manejemen',
  'name_reminder': 'Nama Pengingat',
  'repeat': 'Pengulangan',
  'every_day': 'Setiap Hari',
  'weekly': 'Setiap Minggu',
  'monthly': 'Setiap Bulan',
  'yearly': 'Setiap Tahun',
  'review': 'Ditinjau',
  'approve': 'Disetujui',
  'lending_asset': 'Peminjaman Asset',
  'lending_date': 'Tanggal Peminjaman',
  'return_date': 'Tanggal Pengembalian',
  'submission_step_2': 'Disetujui oleh atasan terkait',
  'submission_step_3': 'GA mencari pemasok untuk diajukan',
  'submission_step_4': 'Disetujui oleh atasan terkait',
  'submission_step_5': 'Disetujui oleh Finance',
  'submission_step_4&5': 'Disetujui oleh atasan terkait & Finance',
  'submission_step_6': 'Pengadaan aset',
  'submission_step_7': 'Pengadaan aset',
  'submission_step_0': 'Pengajuan Aset Selesai',
  'On Process': 'Diproses',
  'Approve': 'Disetujui',
  'Rejected': 'Ditolak',
  'Complete': 'Selesai',
  'added_from': 'Pembuat',
  'date_used': 'Tanggal Digunakan',
  'tracking': 'Pelacakan',
  'yes,approved': 'Iya, Sejutu',
  'find_supplier': 'Tentukan Pemasok',
  'see_all_monitoring_lists': 'Lihat semua daftar monitoring',
  'upload_file_find_supplier': 'Unggah file jpeg, jpg, png, doc, docx, xls, xls (Max 4 MB)',
  'note': 'Catatan',
  'data_supplier': 'Data Pemasok',
  'upload_document': 'Unggah Dokumen',
  'reject_submission': 'Menolak Pengajuan',
  'approve_submission': 'Menyetujui Pengajuan',
  'reason': 'Alasan',
  'send': 'Kirim',
  'comment': 'Komentar',
  'choose_approved_supplier': 'Pilih pemasok disetujui',
  'choose_supplier': 'Pilih Pemasok',
  'info_choose_supplier': 'Silahkan  pilih 1 supplier untuk diteruskan ke purchase order ',
  'submission_details': 'Detail Pengajuan',
  'info_create_purchase_order_1': "Saat ini Anda belum memilik daftar aset yang akan dibeli, ",
  'info_create_purchase_order_2': "klik disini",
  'info_create_purchase_order_3': " untuk menambah daftar beli.",
  'info_po_is_empty': 'Mohon isi barang yang akan dibeli',
  'added': 'Tambahkan',
  'insert_the_discount_amount_and_tax_your_assets': 'Masukkan jumlah diskon dan tax asetmu',
  'insert_discount_and_tax_here': 'Masukkan diskon dan tax disini',
  'discount': 'Diskon',
  'total_discount': 'Total Diskon',
  'total_payment': 'Total Pembayaran',
  'tax': 'Pajak',
  'total_tax': 'Total Pajak',
  'form_purchase': 'Formulir Pemesanan',
  'asset_name': 'Nama Aset',
  'create_purchase_order': 'Buat Pesanan Pembelian',
  'paid': 'Terbayar',
  'un_paid': 'Belum Terbayar',
  'upload_invoice': 'Unggah Invoice',
  'create_submission': 'Tambah Pengajuan',
  'submission_rejected': 'Pengajuan ditolak',
  'submission_approved': 'Pengajuan disetujui',
  'submission_selected_supplier': 'Pemasok dipilih',
  'set_supplier': 'Mengatur Pemasok',
  'please_add_a_suppliers': 'Silahkan tambahkan pemasok',
  'created_purchase_order': 'Membuat pesanan pembelian',
  'please_fill_in_the_items_to_purchase': 'Silakan isi barang yang akan dibeli',
};